info:
  name: products
  type: http
  seq: 1

http:
  method: GET
  url: "{{server}}/product/api/v1/arizona/products"
  headers:
    - name: x-tenantid-1
      value: ec
  auth:
    type: bearer
    token: "{{token}}"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
  forwardAuthorizationHeader: true
